# Generated by Django 5.2.3 on 2025-06-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_deleteaccuntslist_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
