# Generated by Django 5.2.3 on 2025-06-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_emailotp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='otp_exp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
