# Generated by Django 5.2.3 on 2025-06-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_customusermodel_otp_customusermodel_otp_exp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='otp_exp',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='otp_verified',
        ),
    ]
